### ISSUE TITLE
Both xposed and root versions are not working under OnePlus One OxygenOS(Android 5.0.2)

### ISSUE THREAD

**Issue by antitake** [GhostFlying/LocationReportEnabler#13]
Xposed binary version 61, compiled for SDK 21
Device: A0001 (OnePlus), Android version 5.0.2 (SDK 21)
ROM: A0001_12_150403
Build fingerprint: ONEPLUS/A0001/A0001:5.0.2/LRX22G/34:user/release-keys
Platform: armeabi-v7a, 32-bit binary, system server: yes
SELinux enabled: yes, enforcing: yes

![screenshot_2015-04-13-21-13-18](https://cloud.githubusercontent.com/assets/6289638/7116217/73717ee8-e222-11e4-859b-15d251fa5728.png)
![screenshot_2015-04-13-21-13-34](https://cloud.githubusercontent.com/assets/6289638/7116218/737315b4-e222-11e4-8dc9-c074928537d7.png)
![screenshot_2015-04-13-21-15-59](https://cloud.githubusercontent.com/assets/6289638/7116219/73740410-e222-11e4-991f-cc4cc3ef7f5a.png)

Log file should be available at <http://qiniu-up.qiniudn.com/1957374d128509ec78c44583641decf9>, but I can't find anything useable.

**Comment by GhostFlying** [comment]
I removed the log so that the logcat or xposed log do not any info.

For gms 7.0, I suggest you to clear the all data of it and reboot immediately, it may cache the operator's info during some time.

If this do not work, I may compiled a debug version for u to figure out the reason.

**Comment by antitake** [comment]
It works now after I rolling back to v6.5 play service and update to v7.0 after reboot, thanks a lot!
