### ISSUE TITLE
cm12s不成功

### ISSUE THREAD

**Issue by laifuer** [GhostFlying/LocationReportEnabler#14]
设备：OnePlus One
系统：CM12s
原来我是使用cm11s然后加载init.d脚本
#!/system/bin/sh

if [ -e /etc/no_fix_sim ]; then
	exit 0
fi

#We will proceed if either
#1. gsm.sim.state has a READY value
#2. 100s timeout ( this would happen if we are booting without sim card )
loop_cnt=10

for i in `seq $loop_cnt`
do
	sleep 10;
	state=`getprop gsm.sim.state`
	if [ -n $state ] && [ $state = "READY" ] ; then
		echo "sim is ready";
		break;
	fi
done

num=`getprop fix.sim.debug`
if [ -z $num ] ; then
    	#We have not initialized this variable before
	setprop fix.sim.debug 1
fi

num=$(( $num + 1 ))
setprop  fix.sim.debug $num

#wait for sometime to waive the potential glitch
sleep 5
#Now do the fixing
setprop gsm.sim.operator.alpha 		"Verizon"
setprop gsm.sim.operator.iso-country 	"us"
setprop gsm.sim.operator.numeric    	"310004"
原来好好的，可是现在升级cm12s基于android5.0.2无效，然后我就用了你的这个非xposed版，还是无效

**Comment by GhostFlying** [comment]
尝试清除 Google Play Service 数据并重启

**Comment by laifuer** [comment]
已经清除了，还是不行

**Comment by laifuer** [comment]
恢复cm12s原厂google play服务后开启成功
通过google play市场更新最新版本后重启，依然成功

**Comment by zwpaper** [comment]
cm12s 安装后找不到图标是怎么回事？
