### ISSUE TITLE
HTC one 802D无法开启位置报告

### ISSUE THREAD

**Issue by lkyyxf** [GhostFlying/LocationReportEnabler#15]
android5.0.2 sense 7.0 xposed 3.0alpha1 重启多次还是无法开启位置报告，是因为双卡的原因吗？

**Comment by GhostFlying** [comment]
很可能是，我并不知道双卡设备在获取运营商信息时有何区别

**Comment by lkyyxf** [comment]
…等了一天都没开启才来问…结果你一回复我就发现已经自己开启了…不愧是大神😂

**Comment by wxg4net** [comment]
我也遇到过 重启后，需要等一会才显示位置报告开启。
