### ISSUE TITLE
建议添加对Google App的支持

### ISSUE THREAD

**Issue by HankAviator** [GhostFlying/LocationReportEnabler#16]
貌似Google app的随时聆听和声音解锁功能也会依靠相同机制判断，能否将这个机制也应用到Google app上？

**Comment by GhostFlying** [comment]
我这里来看，Google Apps 的这两个是开启的，应该是直接读取得 gms 数据，也许是语言问题？

另外，非 Xposed 版本修改实际上是全局的，所有应用都会收到影响。
