### ISSUE TITLE
有没有什么办法让特定app规避非Xposed版的影响

### ISSUE THREAD

**Issue by TaikooS** [GhostFlying/LocationReportEnabler#17]
首先感谢作者，让我们可以省去繁琐的步骤即可一步到位开启Google Now。

前些天刷了机后把网易云音乐装回来，发现原本使用的联通畅听包服务显示为未使用，试图使用的时候提示我“不是联通用户”，似乎就是由于LRE的作用所致了。

我手机是Sony Z3 D6653 台版 5.0.2系统，由于安装Xposed后启用/禁用任何Module都会导致Bootloop，所以只能使用非Xposed版，虽然我看到作者说该版作的修改是全局性的，但还是想问问有没有其他途径达到绕过特定APP的方法，感谢!

**Comment by GhostFlying** [comment]
目前没看到，不过有个思路是看 网易云音乐 判断是读的哪个属性，解锁只需要读 operator code，如果网易读的是其它属性还有救，不然是没办法的

**Comment by TaikooS** [comment]
唔……这个就超出我的能力范围了。看来只能期望Xposed的后续更新了，感谢你的回答。
