### ISSUE TITLE
Google Maps satellite view is wrong

### ISSUE THREAD

**Issue by GhostFlying** [GhostFlying/LocationReportEnabler#2]
I found the problem that no matter how the variables are set, there must be one view    between map and satellite is wrong. And I suppose it is a bug by Google, but if anyone has the way to solve, please write down here, thank you.

**Comment by cokebar** [comment]
目前找的的方法是 修改hosts文件 将若干域名劫持到maps.google.cn的IP 这样可以消除偏移：
http://cokebar.info/archives/1156
但是问题是，这个劫持可能会影响google其他app的。。 我在路由器上改了hosts，结果PC上的chrome环聊插件就发不出消息了，其他手机上的app还未测试
能否只劫持google maps一个app的域名解析到maps.google.cn，这样就可以解决偏移了

**Comment by HankAviator** [comment]
只针对Play服务进行伪装是不会导致地图偏移的。如果对地图也使用伪装信息，则会导致普通地图便宜。卫星模式似乎使用了新的数据，因此无论如何都会有偏移。

**Comment by isaacbao69** [comment]
5.1+9.5.1地图和卫星是重合的，但是定位偏移。

**Comment by xyxcn** [comment]
我记得这是一个很老的问题。。。在iPhone4那个年代 Cydia上就有n多修正地图偏移的插件了。。作者可以去找下。。然后写个详细点的反馈给谷歌地图。。。我没事也老给他们写 虽然他们都不看吧。。包括之前中文语音下强制关闭Google now。。。

**Comment by xyxcn** [comment]
btw 谢谢作者发布这个小插件 很有用0 0.。。对于海归档。。

**Comment by GhostFlying** [comment]
其实这是一个Google以前曾经解决，但是后来突然又出现的问题，5.1上目前测试似乎也解决了

**Comment by xyxcn** [comment]
0 0 我的貌似还是灭的。。。。然后那个Google now 跟 location service也是灭的。。

还一个事额 主页上下来是1.1版本 是根据5.1更新了的？我各种清缓存飞行模式 重新扫描运营商种种。。重启 折腾 了一组还是不行。。

This is the test apk for 5.1:https://drive.google.com/file/d/0BxNnvIFWQpP2NFV3WEQzSWVNNEE/view?usp=sharing
due to the different signature, it need uninstall the old apk.

这个需要permission。。这个跟主页上的是一个版本不

谢谢0 0

**Comment by GhostFlying** [comment]
1.1版本是为5.1优化的版本，但是由于GMS的机制改变，我推荐的做法是，运行，清除Play Service（就是 Google Setting 那个应用）所有数据，重启，在我地方基本能稳定开启

**Comment by xyxcn** [comment]
噗哈哈哈哈哈 刚才一看莫名其妙的就开启了。。跟gfan上的一堆人一样- -。。。。谢谢作者了。
求多问一句 在不翻wall的时候 Google now会更新么0 0。因为news里面的新闻 直接点击的话 都得先从Google那绕一下。。等于不翻的话就没法用。。

**Comment by xyxcn** [comment]
噗// 发现地图也好了。。好神奇0 0.。。。

**Comment by GhostFlying** [comment]
不翻墙，Google now 基本等于不存在

**Comment by xyxcn** [comment]
再伸手一次。求问作者用啥翻。难道常年挂着shadowsocks 或者fqrouther么…
2015年3月20日 上午12:48于 GhostFlying <notifications@github.com>写道：不翻墙，Google now 基本等于不存在

**Comment by GhostFlying** [comment]
是，常年ss

**Comment by xyxcn** [comment]
谢谢～
2015年3月20日 上午9:20于 GhostFlying <notifications@github.com>写道：是，常年ss

**Comment by cool-delete** [comment]
我也发现了 googlemap里面的地图是高德的火星地图 googlemap有处理把真实坐标计算成火星坐标的
不过google的另外产品就没有了 例如位置报告  googlenow 这些坐标传回去其实都没经过处理 所以如果你在pc的googlemap上看你手机的位置 就会偏移
