### ISSUE TITLE
moto x一代无法打开location history

### ISSUE THREAD

**Issue by whinamp** [GhostFlying/LocationReportEnabler#21]
在清理了Google play services数据，退出账号重新登录以后打开了Google now，虽然location history那里不再是not available in China，但一直是retrieving或者can't reach Google retrieve settings, please try again later.无论是shadowsocks还是其他穿墙器都不管用，这该怎么解决？

**Comment by whinamp** [comment]
对了，系统是Android 5.0.2

**Comment by GhostFlying** [comment]
这现象似乎还是连接服务器的问题，试下换个ss服务器？
