### ISSUE TITLE
请问下作者，支持最新的安卓M吗？非常感谢作者你提供这么好的插件，由衷的谢谢你。

### ISSUE THREAD

**Issue by BoluoKING** [GhostFlying/LocationReportEnabler#28]
作者你好，我N6用你的这个小插件完美解决了不能开启位置服务的问题。现在安卓有最新的M版了，希望作者能更新下，等这个插件支持安卓M了，我就把N6升级成安卓M。
当然可能这个旧的版本也支持，我没有试。如果支持，请作者你告知一下。
非常感谢作者你提供这么好的插件，由衷的谢谢你。

**Comment by GhostFlying** [comment]
我刚刷完 6.0，可以正常开启没有异常。

**Comment by BoluoKING** [comment]
谢谢您。再问下作者，现在有支持m的x框架吗？

**Comment by GhostFlying** [comment]
Xposed 应该没有

**Comment by BoluoKING** [comment]
谢谢你的回答！

**Comment by BoluoKING** [comment]
请问作者你是怎么root的？

**Comment by GhostFlying** [comment]
Twrp+supersu+内核
