### ISSUE TITLE
Nexus 6 with stock 5.1.1使用xposed framework版本的stk问题

### ISSUE THREAD

**Issue by elamarkant** [GhostFlying/LocationReportEnabler#30]
使用xposed版本之后功能一切正常，但是stk.apk就在launcher里消失了，没法使用，这是什么问题？我还有些需要用到sim toolkit的菜单，谢谢！

**Comment by GhostFlying** [comment]
Google Now launcher 直接用的 gms 的数据吧。。这种问题基本无解。
