### ISSUE TITLE
MM下的xposed版本无法使用

### ISSUE THREAD

**Issue by Roger-Lee** [GhostFlying/LocationReportEnabler#31]
15号有官方支持Android6.0的xposed框架了，Nexus5X下模块不起作用，非xposed版正常

**Comment by GhostFlying** [comment]
我的 N6 刷不进框架。。等我折腾完看下。。

**Comment by Roger-Lee** [comment]
好的，感谢

**Comment by Roger-Lee** [comment]
多清除了几次google play服务的数据，重启后可以打开位置服务了，但是中间遇到一次无法启动，两次自动重启，似乎xposed还不太稳定啊。。。

有没有办法不清除play服务数据就可以生效的？

**Comment by GhostFlying** [comment]
不清除数据还是不太可能的。。我刷了 v78 感觉还行
