### ISSUE TITLE
MIUI - Xiaomi Phones

### ISSUE THREAD

**Issue by ermalx** [GhostFlying/LocationReportEnabler#35]
Anyone had any experience enabling location history on Xiaomi phones? I have installed and checked the numeric value has changed to 310030, but still location history will not be enabled. Any suggestion?

**Comment by GhostFlying** [comment]
Dual sim or single? I have no condition to test dual sim phone and it may have some problems.

**Comment by ermalx** [comment]
Usually i have tested only with 2 sim cards. sometimes it works sometimes doesn't. When I remove one sim it works. Also I have checked that only the value for the first sim has changed. Anyway it works with one sim perfectly. Thank You for the last update!

**Comment by GhostFlying** [comment]
version 1.4.0 adds functions to support dual sim devices, u can try it from the release page.
