### ISSUE TITLE
Cannot use after reinstalling

### ISSUE THREAD

**Issue by SkyZH** [GhostFlying/LocationReportEnabler#36]
When I come back from a foreign country and reinstall this application (root version), I cannot find the application in launcher until I manually run `pm enable com.ghostflying.locationreportenabler/.MainActivity`.

**Comment by GhostFlying** [comment]
Sorry I do not consider this situation, I will try to find a better way.

**Comment by GhostFlying** [comment]
now u can clear data to show launcher again from version 1.4.0, u can get it from the release page.
