### ISSUE TITLE
Didn't work for Youtube Music

### ISSUE THREAD

**Issue by baozijianke** [GhostFlying/LocationReportEnabler#37]
对 Youtube Music 不管用啊。 仍然是说 在您的地区不提供服务。

**Comment by GhostFlying** [comment]
什么版本的？

**Comment by GhostFlying** [comment]
以及可以描述下如何复现么，我装了 Youtube Red 似乎并没有什么提示。

**Comment by baozijianke** [comment]
（尴尬脸） 原来是我VPN的问题…… 我换了一个VPN就没问题了，之前用的是Lantern，现在换了自己部署在US的SS。真是不要好意思。可以关闭这个issue了。
