### ISSUE TITLE
App Icon automatic hide

### ISSUE THREAD

**Issue by ermalx** [GhostFlying/LocationReportEnabler#40]
The latest version does not hide automatically the app icon. is it possible to hide the icon because it is only in chinese?

**Comment by GhostFlying** [comment]
Due to someone do not want to hide the icon automatically, now this function is optional and you should check the last choice in the app.

I will try to add en version some time later.

**Comment by ermalx** [comment]
Thank You Ghost! Still I have some problems with the app as location reporting sometimes does not activate even though the sim provider code has changed.

**Comment by GhostFlying** [comment]
What causes this mostly is the cache of Google Service Framework, now the version 1.3.1 can help u clear the data of these.  U can check the second choice to clear the gms and the third one to clear maps, and the fourth one is to reboot.

**Comment by ermalx** [comment]
Thank You one more time Ghost. I will try that. All the best!!!

**Comment by GhostFlying** [comment]
En version added, u can update if u needed.
