### ISSUE TITLE
root版下载完打不开

### ISSUE THREAD

**Issue by nemo95** [GhostFlying/LocationReportEnabler#41]
是不是传错了？

**Comment by GhostFlying** [comment]
我测试似乎没什么问题，你下载的多大？

**Comment by nemo95** [comment]
1.17MB

**Comment by nemo95** [comment]
https://drive.google.com/file/d/0BxNnvIFWQpP2aGszc3lYRWRCSzg/view?usp=sharing
用的这个链接，手机是Nexus6P

**Comment by GhostFlying** [comment]
我这边测试似乎并没有什么问题

**Comment by nemo95** [comment]
哦，先卸载旧版本就能装了，谢谢了。
