### ISSUE TITLE
1.3.0版本安装失败

### ISSUE THREAD

**Issue by xfree86** [GhostFlying/LocationReportEnabler#42]
在xposed里面更新安装1.3.0，安装失败，显示“应用未安装” 系统为Android 6.0.1 魔趣201605131643

**Comment by GhostFlying** [comment]
因为 key 变了，卸载安装就好了

**Comment by xfree86** [comment]
多谢回复，先卸载再重新安装成功，然而google maps 的时间轴还是显示“无法连接到地图，请过几分钟再试”，已开梯子（其他都正常）。

**Comment by GhostFlying** [comment]
Google Maps 需要清除数据

**Comment by xfree86** [comment]
OK了，多谢！
