### ISSUE TITLE
N beta4 开启失败

### ISSUE THREAD

**Issue by seraph758** [GhostFlying/LocationReportEnabler#44]
清空了service还是开启失败

**Comment by GhostFlying** [comment]
我这里是正常的，你是什么设备？

**Comment by seraph758** [comment]
N6 清空了seevice没开启，然后我又试着恢复出场先让他开启，然后安装这个app，定位还是关闭了

**Comment by GhostFlying** [comment]
哪个版本的 LRE

**Comment by seraph758** [comment]
装的3月份那个支持N的版本，有没有什么办法能查看是否修改成功呢

**Comment by kcschan** [comment]
只要有足够新的superSU(2.72, 2.74)，无需使用3月份那个专门用于支持N的版本

seraph758 <notifications@github.com>于2016年6月20日周一 下午2:01写道：

**Comment by seraph758** [comment]
我现在装的supersu是2.74的，你的意思是说不需要专门支持N的，用那个5月份更新的也可以支持android n beta4吗？

**Comment by GhostFlying** [comment]
是，在 supersu 支持 N 后，就没有必要用那个专门给 n 准备的版本了

**Comment by seraph758** [comment]
好的，明白了。请问除了清空service还需要清空别的吗

**Comment by GhostFlying** [comment]
理论上应该不需要，时间轴的话可能需要清地图
