### ISSUE TITLE
Android N正式版上不工作

### ISSUE THREAD

**Issue by baraja** [GhostFlying/LocationReportEnabler#46]
不起作用，重启后，gsm.sim.operator.numeric还是国内的运营商

**Comment by GhostFlying** [comment]
预览版上没问题，正式版我手上的 N6 还没推送，出了我看下

**Comment by Jamesits** [comment]
Nexus 5x，Android 7.0 正式版下工作正常

**Comment by LicoferLuigic** [comment]
Nexus 6p，Android 7.0 NRD90M不起作用

**Comment by GhostFlying** [comment]
N6 NBD90Z 下并未发现异常
