### ISSUE TITLE
nexus6 androind N正式版不能正常工作

### ISSUE THREAD

**Issue by lingbaoboy** [GhostFlying/LocationReportEnabler#47]
nexus6 androind N正式版（7.0.0 (NBD90Z)）不能正常工作
坐等更新

**Comment by jeffers3n** [comment]
N6 N同等。

**Comment by GhostFlying** [comment]
我在 N6 正式版下未发现问题，是否可以提供 getprop 信息？

**Comment by lingbaoboy** [comment]
你用的是General version还是Android N version
我两个版本都测试就是不行

**Comment by lingbaoboy** [comment]
getprop 怎么获取额

**Comment by baraja** [comment]
是不是说root一定要用phh superuser而不能是supersu？然后使用Android N version取代General version？

**Comment by GhostFlying** [comment]
没有这个意思，N version 只是为了解决一个 selinux 的问题，supersu 没这个问题不需要。

任一终端模拟器输入 getprop | gsm 即可

**Comment by GhostFlying** [comment]
getprop | grep gsm

**Comment by test1943** [comment]
遇到同样的情况，勾选前面三项(不勾Reboot)，确定后再重启貌似就可以了。

**Comment by lingbaoboy** [comment]
如@test1943 所言，使用通用版，可以了。

**Comment by GhostFlying** [comment]
Ok，N 的专版应该已经不再需要，我先把他移除了
