### ISSUE TITLE
6p 7.0正式版 10月补丁，成功，但是时间轴“无法连接到地图，请过几分钟后再试”

### ISSUE THREAD

**Issue by tianfire** [GhostFlying/LocationReportEnabler#48]
及时好用 地理位置也成功开启，唯有时间轴有问题

**Comment by jimmy19990** [comment]
我的也是，时间轴现在只能在开美国代理的情况下才能用。

**Comment by GhostFlying** [comment]
时间轴有独立的 ip 黑名单，请先确认自己的 ip 没有在其中
Jimmy Zhang <notifications@github.com>于2016年10月12日 周三下午1:26写道：

**Comment by tianfire** [comment]
好吧 我香港vpn 应该在黑名单里
