### ISSUE TITLE
Serious crashes in Samsung TouchWiz based Android 4.4.2

### ISSUE THREAD

**Issue by legendtang** [GhostFlying/LocationReportEnabler#5]
When I approved it with ROOT then reboot, I checked the Location Report app and it still told me Not Available in China even after a long wait.

But when I reboot again something weird happens. An auto power off was executed on each boot after a few seconds. So I thought there is something incompatible with Samsung's firmware. But when I tried to uninstall, once clicked the phone will power off, every time.

And I get to disapprove ROOT quickly, uninstall successfully. BUT,

It still has the problem, auto power-off after boot into system for a few seconds. And I found that once clicked Google Drive app it will power-off immediately(Maybe `Google Service` related).

Until now, I had no idea to deal with the problem except for a ROM flash, which I don't want to do now.

Sorry that I can't not `log cat` any data as soon as it appears. Please do some tests on Samsung's device and noted that this issue is SERIOUS.

My device is Samsung Galaxy S4 LTE GT-I9505 with latest firmware and Google Play Services. For further information, feel free to ask me.

**Comment by legendtang** [comment]
I do some tricks to install the version provided by the second link.

Though it works fine with no more crashes but both Google Now and LRE are unavailable after data clear

**Comment by GhostFlying** [comment]
I've no idea about the first one. The app just run setprop command, it may not work but should not cause any other problems like yours in my opinion. I guess it may related with the special root status in the device. I will try to find a similar device to test.

For the second one, can you provide me the value of the three variables start with gsm? You can get there by adb or terminal emulator using getprop command.

**Comment by legendtang** [comment]
Sorry for the delay, after the examination finally I have time to test it. Surprisingly, after an OTA it works well, seems to be TouchWiz Launcher related. I have no idea how to reproduce the problem.

The issue could close for now.
Thank you!

**Comment by GhostFlying** [comment]
I will try to find the problem once I can reproduce the problem, thanks for your feedback.
