### ISSUE TITLE
非Xposed版APN问题

### ISSUE THREAD

**Issue by nexusman2016** [GhostFlying/LocationReportEnabler#51]
系统版本 Android 6.0.1
使用非Xposed版导致APN变化且无法修改，收不到发不了彩信，改不了接入点
请问这个问题在未来的版本中是否会考虑解决或者改善呢？
谢谢！

PS 这个应用非常赞，谢谢作者

**Comment by GhostFlying** [comment]
在现有的实现方式下暂时没什么好办法解决，抱歉。
