### ISSUE TITLE
Not functioning on OnePlus 3T with Oxygen OS 4.0.2 & OnePlus Launcher.

### ISSUE THREAD

**Issue by wck963** [GhostFlying/LocationReportEnabler#56]
As title.

**Comment by GhostFlying** [comment]
Do not hide launcher icon ? It's a known issue and will be fixed soon after
my laptop is back.

**Comment by Harry-Chen** [comment]
同样是 Oxygen OS 4.0.2
事实上除了无法隐藏图标（也不是什么问题），似乎没有发挥作用。
用 `getprop` 的确可以看到属性被改了，但是 Google 设置里依旧显示无法在中国使用。
（重启、清空 Play Service 数据、打开飞行、重新登录 Google 账户多次）

**Comment by Harry-Chen** [comment]
抱歉，我更正一下。
重启以后立刻 getprop 发现那两个属性并没有被更改。
没有用任何启动管理/阻止运行之类的软件，也打开了 SuperSU 的那个启动时允许所有请求的选项。

**Comment by GhostFlying** [comment]
这个看起来比较奇怪，我手上没有一加不知道是个例还是系统的问题，以及相关权限你都给了么？
Harry Chen <notifications@github.com>于2017年1月21日 周六下午8:41写道：

**Comment by GhostFlying** [comment]
没有立刻变其实是正常的，因为 android 上很难做到系统启动后第一时间运行，接受系统广播本身的确需要时间，按照设计 lre 会在接收到系统启动和
SIM 卡状态改变的广播时修改属性，在绝大部分情况下应该足以比 GMS 更早。

另外，实际上 GMS 启动后一段时间会重新读取运营商，因此会出现刚启动时不可用，稍后几分钟就可以的情况。
Ghost Flying <ghostflying@gmail.com>于2017年1月21日 周六下午8:45写道：

**Comment by Harry-Chen** [comment]
好的，感谢回复。
事实上我是等到收到 BOOT_COMPLETE 和 SIM_STATE_CHANGED 两个Intent 以后才打开 Play Service 设置的，不过那时候还是显示的不可用状态，大概就是第一次并没有读取到正确的运营商。
我会再试几次的，如果有问题再上报。

**Comment by GhostFlying** [comment]
好的，也感谢反馈，我也会尝试寻找更加可靠的方式，不过这东西机型系统差异的确很大，调试起来非常坑。

**Comment by wck963** [comment]
![image](https://cloud.githubusercontent.com/assets/7414442/22174628/1ee46e7a-e01e-11e6-8b28-671fdd330e03.png)

Finally following this post ( http://www.coolapk.com/apk/org.cafeboy.locationreportenabler ) I succeeded.
But I still not quite sure what finally helps since I tried multiple ways to enable the Google Now feature.

**Comment by wck963** [comment]
Maybe more detailed wiki would be added to this repo, including multiple ways to work with the tool @GhostFlying created. I shall say thank you, above all.

**Comment by GhostFlying** [comment]
Actually I find a minor issue about the behavior change after Android 7.0
but I am not sure it is the cause as my Nexus 6 with 7.1.1 works well but I
will try to fix it next version.

**Comment by ZengLeiPro** [comment]
同样机型，同样系统版本，同样遇到这个问题，不知后续能否修复，谢谢。

**Comment by codgician** [comment]
已经明白问题所在，原因是氧OS默认关闭了该软件的自动启动。
请前往设置 - 应用 - 左上角的齿轮图标，拉到菜单最下面，找到应用自启，允许Location Report Enabler自启即可。
请上述遇到该问题的朋友测试。
