### ISSUE TITLE
运营商代码和国家问题。

### ISSUE THREAD

**Issue by SakuraSa233** [GhostFlying/LocationReportEnabler#59]
为什么我总觉得他们反了，运营商代码那里填的jp，国家却填44040。（自己修改后
QAQ

**Comment by GhostFlying** [comment]
1.4.1 是反的，后续已修正
SakuraSa233 <notifications@github.com>于2017年2月25日 周六下午5:05写道：

**Comment by SakuraSa233** [comment]
等下也许我会帮乃提交一下日语的翻译（呼呼

**Comment by SakuraSa233** [comment]
话说乃有没有注册一个酷安开发者账号的想法，如是问道

**Comment by GhostFlying** [comment]
考虑过，懒
