### ISSUE TITLE
确认 影响一款华为手机电信版 ctnet ctwap联网模式的选择

### ISSUE THREAD

**Issue by wxg4net** [GhostFlying/LocationReportEnabler#6]
开启后，无法点亮模式选择了

**Comment by GhostFlying** [comment]
可以具体描述下你用的版本和过程么

**Comment by wxg4net** [comment]
其实我应该贴下log
D/ToolBox (22028): getDesiredState
D/ToolBox (22028): getTriState
D/ToolBox (22028): isSimStateReady: dual card device, simState is 5
D/ToolBox (22028): apnCheck: simOperator is 310030, networkOperator is 46003, isCTApn is set to false
D/ToolBox (22028): apnCheck: simOperator is not equal to networkOperator
D/ToolBox (22028): apnCheck: networkOperator is in China
D/ToolBox (22028): apnCheck: other region simOperator is got, mCanChangeToCTWap is set to false
D/ToolBox (22028): apnCheck: finally, isCTApn is set to false
D/ToolBox (22028): getTriState: isCTApn is false or preferredDataSubscription is not 0, return APN_STATE_OFF
D/ToolBox (22028): requestStateChange: desiredState is 5
D/ToolBox (22028): requestStateChange: use press Button no response ! + mCanChangeToCTWap = false

**Comment by GhostFlying** [comment]
这个步骤在有信号后多久？是连着的么？

**Comment by wxg4net** [comment]
这个步骤是在开机有电信信号连接上之后操作的。不管多久都无法选择。有个现象可能需要说明下。LocationReportEnabler获取root权限的系统提示似乎出现的比较晚。我测试有时会在连接上电信信号后才出现.。

**Comment by GhostFlying** [comment]
手动操作？这会比较难办，这个现象基本上还是修改过早了，如果是手动完成的话，程序可能很难选择正确的时间。

**Comment by wxg4net** [comment]
不是很明白你的意思。LocationReportEnabler 是开机自动运行的。

**Comment by GhostFlying** [comment]
你用的是哪个版本的，Full 还是 tiny

**Comment by wxg4net** [comment]
tiny版本 我市场是解锁的
2015年1月24日 下午4:43于 "GhostFlying" <notifications@github.com>写道：

> 你用的是哪个版本的，Full 还是 tiny
>

**Comment by GhostFlying** [comment]
你的那个所谓 ToolBox 是手动选择的么？

**Comment by wxg4net** [comment]
是的 截图
2015年1月24日 下午4:52于 "GhostFlying" <notifications@github.com>写道：

**Comment by GhostFlying** [comment]
这就比较麻烦了，这几天我会给一个监听网络连接的版本，到时候你可以试下，但不确定这种会不会有效

**Comment by wxg4net** [comment]
我晕 邮件回复不带截图哦。我问下。这个修改sim参数是应该在sim注册后网络链接前发生的么

**Comment by wxg4net** [comment]
截图：接入点（灰色）
http://t.cn/RZQ3V5w

**Comment by GhostFlying** [comment]
不一定，在gms读这个参数前就可以，但具体什么时候读很难确定，只能说一定在有信号之后

**Comment by wxg4net** [comment]
OK
2015年1月24日 下午8:05于 "GhostFlying" <notifications@github.com>写道：

> 不一定，在gms读这个参数前就可以，但具体什么时候读很难确定，只能说一定在有信号之后
>

**Comment by GhostFlying** [comment]
另外看截图，你这个似乎是切换前就会有网络连接？这个很可能基本无解。

**Comment by wxg4net** [comment]
网络连接v？是指移动网络么。是的。使用前是两个都是亮的，然后可以切换。目前不能亮了，也无法切换了。主要是移动网络连接不稳定了。使用前相当稳定。如果你有个这类机器调试就好了

2015年1月24日 下午8:13于 "GhostFlying" <notifications@github.com>写道：
>
> 另外看截图，你这个似乎是切换前就会有网络连接？这个很可能基本无解。
>
> On Sat, Jan 24, 2015, 8:07 PM wxg <notifications@github.com> wrote:
>
> > OK
> > 2015年1月24日 下午8:05于 "GhostFlying" <notifications@github.com>写道：
> >
> > > 不一定，在gms读这个参数前就可以，但具体什么时候读很难确定，只能说一定在有信号之后
> > >
> > > On Sat, Jan 24, 2015, 5:14 PM wxg <notifications@github.com> wrote:
> > >
> > > > 截图：接入点（灰色）
> > > > http://t.cn/RZQ3V5w
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
https://github.com/GhostFlying/LocationReportEnabler/issues/6#issuecomment-71306470>

> >
> > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
https://github.com/GhostFlying/LocationReportEnabler/issues/6#issuecomment-71313915>

> >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
https://github.com/GhostFlying/LocationReportEnabler/issues/6#issuecomment-71313988>
