### ISSUE TITLE
重启手机会提示“LocationReportEnabler 已停止运行”

### ISSUE THREAD

**Issue by Kongloli** [GhostFlying/LocationReportEnabler#61]
重启手机会提示“LocationReportEnabler 已停止运行”，虽然功能上好像不影响，不过还是希望能修复。
Android 版本为：7.1.1，log：
02-26 17:51:58.504  1222  1222 E AndroidRuntime: FATAL EXCEPTION: main
02-26 17:51:58.504  1222  1222 E AndroidRuntime: Process: com.ghostflying.locationreportenabler, PID: 1222
02-26 17:51:58.504  1222  1222 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.ghostflying.locationreportenabler.EnablerReceiver: java.lang.StringIndexOutOfBoundsException: length=100; regionStart=0; regionLength=-1
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3047)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(ActivityThread.java)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: Caused by: java.lang.StringIndexOutOfBoundsException: length=100; regionStart=0; regionLength=-1
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:69)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:53)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at com.ghostflying.locationreportenabler.PropUtil.getShellOutput(PropUtil.java:152)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at com.ghostflying.locationreportenabler.PropUtil.setFakerCarrierForDualCard(PropUtil.java:114)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at com.ghostflying.locationreportenabler.PropUtil.setFakeCarrier(PropUtil.java:100)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at com.ghostflying.locationreportenabler.PropUtil.enableLocationReport(PropUtil.java:46)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at com.ghostflying.locationreportenabler.EnablerReceiver.onReceive(EnablerReceiver.java:24)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3040)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	... 8 more
02-26 17:51:58.504  1222  1222 E AndroidRuntime: FATAL EXCEPTION: main
02-26 17:51:58.504  1222  1222 E AndroidRuntime: Process: com.ghostflying.locationreportenabler, PID: 1222
02-26 17:51:58.504  1222  1222 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.ghostflying.locationreportenabler.EnablerReceiver: java.lang.StringIndexOutOfBoundsException: length=100; regionStart=0; regionLength=-1
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3047)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(ActivityThread.java)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1561)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: Caused by: java.lang.StringIndexOutOfBoundsException: length=100; regionStart=0; regionLength=-1
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:69)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at java.lang.StringFactory.newStringFromBytes(StringFactory.java:53)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at com.ghostflying.locationreportenabler.PropUtil.getShellOutput(PropUtil.java:152)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at com.ghostflying.locationreportenabler.PropUtil.setFakerCarrierForDualCard(PropUtil.java:114)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at com.ghostflying.locationreportenabler.PropUtil.setFakeCarrier(PropUtil.java:100)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at com.ghostflying.locationreportenabler.PropUtil.enableLocationReport(PropUtil.java:46)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at com.ghostflying.locationreportenabler.EnablerReceiver.onReceive(EnablerReceiver.java:24)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3040)
02-26 17:51:58.504  1222  1222 E AndroidRuntime: 	... 8 more

**Comment by GhostFlying** [comment]
可以给一下设备信息么？什么设备，单卡双卡？以及 LRE 的版本

**Comment by Kongloli** [comment]
设备是：Nexus 5 (hammerhead)，单卡，LRE版本是：1.4.4 。

GhostFlying <notifications@github.com>于2017年2月26日周日 19:19写道：

> 可以给一下设备信息么？什么设备，单卡双卡？以及 LRE 的版本
>

**Comment by GhostFlying** [comment]
看了下大概找到了问题，不过最近有点事，应该会稍后修复

**Comment by Kongloli** [comment]
好的，谢谢。

GhostFlying <notifications@github.com>于2017年2月26日周日 21:59写道：

**Comment by GhostFlying** [comment]
fixed by 51e4e5ef901a1352e982c73572f25ddd77d1bf8b
