### ISSUE TITLE
加入从最近任务列表隐藏功能就更好了

### ISSUE THREAD

**Issue by wuchjun** [GhostFlying/LocationReportEnabler#64]
平时也不需要打开，但是加了锁后一直留在最近任务，不加锁又会被后台清理导致下次开机无法自启动，希望能加入从最近任务列表隐藏功能

**Comment by GhostFlying** [comment]
单纯杀进程不影响开机自启吧，建议你检查下自启动设置。

**Comment by wuchjun** [comment]
会的，普通清理不会（虽然查看正在运行的服务没有看到，但是点开app详情页面还是可以看到app的强行停止可点），但是深度清理（强行停止，不留后台清理方式，7.1.1后通知栏老是有正在运行提示，暂时用这个）就会导致下次开机不再启动，就像如果第一次安装没有打开过只加入开机自启动列表也会开机无法自启

**Comment by GhostFlying** [comment]
不是很懂各种奇怪的清理，后续有空再说吧

**Comment by wuchjun** [comment]
fork下来加了行代码，自己搞定了，用着先，还有问一下play这个root版下架了吗？找不到你发的只找到另外一个作者发的

**Comment by GhostFlying** [comment]
我就没成功上架过，被拒了
