### ISSUE TITLE
volte competitive

### ISSUE THREAD

**Issue by tkisme** [GhostFlying/LocationReportEnabler#67]
when volte on,this will not work anymore.
See comments on http://coolapk.com/apk/com.ghostflying.locationreportenabler
Someone have the same issue

**Comment by tkisme** [comment]
![image](https://cloud.githubusercontent.com/assets/5886048/25270743/42d27c46-26b4-11e7-958d-4c981edabf7a.png)

**Comment by GhostFlying** [comment]
I am confused by what you said. which one is your problem?  Is LRE not work
when voLTE on or voLTE not work when LRE used.

**Comment by tkisme** [comment]
voLTE not work when LRE used.

**Comment by simonsmh** [comment]
You may met this problem on some of devices such as Oneplus Oxygen/H2 OS because they choose to enable volte support by detecting ISP.

**Comment by tkisme** [comment]
@simonsmh thank you!

**Comment by simonsmh** [comment]
额，排查之后发现，GSM numeric设置成310310（T-Mobile）即可强制开启oos的volte/vowifi选项，不知道对你有没有帮助。。

**Comment by tkisme** [comment]
居然可以，神奇神奇
