### ISSUE TITLE
OnePlus One CM12 LocationReportEnabler_xposed的问题

### ISSUE THREAD

**Issue by weizhangjian** [GhostFlying/LocationReportEnabler#7]
设备：OnePlus One
系统：CM12 0304每夜版 安卓5.02
Xposed：3.0 alpha1

已经去除了开机sim卡密码。开机xposed有加载该模块，但是从终端上看还是没有改掉相应的数据。位置报告也无法开启。

![screenshot_2015-03-09-12-57-08](https://cloud.githubusercontent.com/assets/6047456/6550156/546b724c-c65c-11e4-8240-2c6b5b785522.png)
![screenshot_2015-03-09-12-57-32](https://cloud.githubusercontent.com/assets/6047456/6550157/546c680a-c65c-11e4-82d7-ec2d92b6e027.png)
![screenshot_2015-03-09-12-58-03](https://cloud.githubusercontent.com/assets/6047456/6550158/546cebc2-c65c-11e4-8843-1bf0aa7f202b.png)
![screenshot_2015-03-09-12-58-25](https://cloud.githubusercontent.com/assets/6047456/6550159/54741eb0-c65c-11e4-96bf-7238176bf84f.png)

**Comment by weizhangjian** [comment]
Xposed版本安装后没有效果，而且也不能自动启动。没有看到root授权。
一加手机CM12. 3月4日的每夜版，xposed 的测试版。

**Comment by wxg4net** [comment]
既然是xposed就不会看到root授权了吧。 话说能不能支持 低版本的xposed的呢

**Comment by GhostFlying** [comment]
能不能看下 Xposed Installer 里的 Log 里有没有异常输出？

Xposed 的确不会有 root 授权，低版本的支持目前主要是缺乏测试机器，不过这周内应该可以完成。

**Comment by weizhangjian** [comment]
只有看到加载模块的信息，并无异常信息。

**Comment by GhostFlying** [comment]
试下1.0版本？那个应该会有 log 输出，看下有没有？

**Comment by weizhangjian** [comment]
再用这个版本前就是用1.0的版本开启的google now，不过几次重启后就不知道怎么回事失效了。
现在装了xposed了，所以试了下这个版本，还是开不起来。

**Comment by GhostFlying** [comment]
我是指 Xposed 里 的1.0 版本，可以在 Xposed Installer 里搜索下到，另外，Xposed 的修改只对 GMS 起效，因此终端里是看不到变量值的改变的

**Comment by weizhangjian** [comment]
Xposed 里 的1.0 版本 显示无下载地址……

**Comment by GhostFlying** [comment]
抱歉，忘记那个被我删掉了，这里下载：https://drive.google.com/file/d/0BxNnvIFWQpP2LWJ4X1FQOHVUWTA/view?usp=sharing

**Comment by weizhangjian** [comment]
有日志，start hook sim card information
安装完以后，需要重新清google search和开英文吗？

**Comment by wxg4net** [comment]
xposed alpha2出来了... 好像更换到LR的xposed版本

**Comment by GhostFlying** [comment]
5.0 的话理论上不用，有那个日志看起来hook是成功的，无效的事情看起来就很奇怪，你的Play Service 版本是什么？

**Comment by GhostFlying** [comment]
看了下 alpha 2 的更新，有和 cm 相关的修复，可以更新下尝试，如果有可能，我也会在 CM 下测试下

**Comment by weizhangjian** [comment]
试了xposed alpha2的版本，安装LRE xposed1.1的版本，过了半天自动提示重新开启位置报告。

**Comment by GhostFlying** [comment]
Well, 看起来的确是框架的问题
