### ISSUE TITLE
小米6 MIUI8 无效果

### ISSUE THREAD

**Issue by hnliuzesen** [GhostFlying/LocationReportEnabler#74]
之前一直用的这个，Nexus 系列 魅族 都没有问题，昨天用小米6 MIUI8 试了试，发现一直不行，账号退出，GPS关闭，然后设置了清除应用数据重启之后打开 Google App 登陆之后还是提示当前账号不支持 Google Feed。也不知道是什么原因……因为没有装 Xposed 所以直接用的 APK 安装版

**Comment by GhostFlying** [comment]
检查变量，如果没变检查自启动设置

**Comment by hnliuzesen** [comment]
自启动开了，而且重启之后我是先开了一下这个软件，让它后台了，然后开的VPN，然后登陆的账号，我去检查一下变量。
检查了，环境变量310260生效了。
可能是清除数据清除的不够，我去把所有Google相关的都清除了试试。
谢谢提供思路

**Comment by hnliuzesen** [comment]
搞定了，小米6每次启动SELINUX都是Enforcing，改成了Permissive可以了，不知道是不是这个原因，然后运营商设置的310004，因为之前Xprivacy都是用的这个，所以就继续用这个了

**Comment by GhostFlying** [comment]
selinux enforcing 的确会造成设置存在问题，不过一般来说 superSu 可以解决这个问题，有点奇怪
