### ISSUE TITLE
最近似乎失效了

### ISSUE THREAD

**Issue by scavin** [GhostFlying/LocationReportEnabler#78]
6p 前两天突然失效，感觉是 Google 更换了识别方法

**Comment by GhostFlying** [comment]
系统版本？

**Comment by scavin** [comment]
7.1.2 原生系统

**Comment by codgician** [comment]
氧OS 7.1.1 表示暂未发现问题

**Comment by y6yuan** [comment]
小米6, RR OS 7.1.2, 没问题

**Comment by y6yuan** [comment]
小米6, RR OS 7.1.2, 没问题

**Comment by FengkuiChan** [comment]
我之前也试过失效，后来发现是supersu的问题，必须勾选“开机时允许所有授权申请”。如果有用黑域，可能要查看LocationReportEnabler是否被黑域了。
