### ISSUE TITLE
Don't working on Oxygen OS

### ISSUE THREAD

**Issue by LoIIipop** [GhostFlying/LocationReportEnabler#79]
Oneplus5 7.1.1

**Comment by codgician** [comment]
Working on Oxygen OS.
ONEPLUS 3T 7.1.1

**Comment by LoIIipop** [comment]
@codgician How you get it work ? I'm first use the app than add Google account but don't working.

**Comment by GhostFlying** [comment]
Try to review your settings like auto run? You should grant  permissions to
the app.

**Comment by LoIIipop** [comment]
@GhostFlying I have give phone permission and root for the app before apply.

**Comment by kn007** [comment]
OP3T Oxygen OS 4.5.0 Android 7.1.1 Test Pass. Working fine.

**Comment by codgician** [comment]
Confirmed working on OP3T with Open Beta 15.
Please ensure that location report enabler is excluded from Battery Optimization.
You can access that setting by going to Settings -> Battery -> Battery Optimization, find location report enabler and select don't optimize.

**Comment by GhostFlying** [comment]
I have figured out one reason about this issue.

Try yo check your battery advanced optimize option, if it is on, try to turn it off or just set LRE to not optimized.
