### ISSUE TITLE
couldn't work on 5.1

### ISSUE THREAD

**Issue by googolmo** [GhostFlying/LocationReportEnabler#8]
on my nexus 5 os version is 5.1, it's can not make location report on!

**Comment by GhostFlying** [comment]
Which version do you use? Tiny, full or xposed?

**Comment by googolmo** [comment]
@GhostFlying i am use full version, but now i will try tiny version!

**Comment by googolmo** [comment]
@GhostFlying the tiny version is also dosen't work

**Comment by googolmo** [comment]
@GhostFlying now i getprop 'gsm.sim.operator.numeric' is 310030

    shell@hammerhead:/ $ getprop gsm.sim.operator.numeric
    310030

but it's also Not available in China

**Comment by GhostFlying** [comment]
It seems a little strange, I can hardly confirm the cause.

I would test and try to fix it as my Nexus 4 received the 5.1 factory image.

**Comment by googolmo** [comment]
@GhostFlying OK Thx

**Comment by googolmo** [comment]
@GhostFlying Today it's work well....but i don't reboot my phone....

**Comment by GhostFlying** [comment]
..It seems so strange. Do you change your ip?

**Comment by jimbray** [comment]
Same problem! on my nexus 5 os version is 5.1, it's can not make location report on! it's also Not available in China

**Comment by jimbray** [comment]
It is work fine now.It seem like will take a few time to enable location

**Comment by isaacbao69** [comment]
在5.1上不行。刚装了之后，google now里地址相关的card出来了，但是location reporting还是not avaliable in china。所以google fit也不工作。

**Comment by GhostFlying** [comment]
如果可以，请给出Play Service 版本

**Comment by isaacbao69** [comment]
Google Play services 6.7.76
就在几分钟前突然就好了。

**Comment by iliuweiming** [comment]
play service 版本同上，nexus 5 android 5.1 使用的tiny版本，但是用不了 ，期待作者fix it，毕竟android 5.1的xposed还要等很久估计

thanks

**Comment by GhostFlying** [comment]
I will try to fix it, but it need some time as the busy work.

**Comment by GhostFlying** [comment]
This is the test apk for 5.1, due to the different signature, it need uninstall the old apk.

I tested for many times and it seems that the gms on 5.1 may cache the operator's information, so it may not take effect immediately.

I suggested you to enable the "Enable su during boot" and clear the data of Google Play Service, it may take effect after several times of reboot.

**Comment by iliuweiming** [comment]
It works, great job

**Comment by GhostFlying** [comment]
I released a new version. It can enable the location report on my Nexus 6, you can find the link in the readme.

**Comment by iliuweiming** [comment]
The new version still works, thanks.

**Comment by GhostFlying** [comment]
I think the issue is solved.
