### ISSUE TITLE
lineage15.1运行LRE以后被叫无响应（Moto Z）

### ISSUE THREAD

**Issue by HuoDaxia** [GhostFlying/LocationReportEnabler#85]
MotoZ反复测试，运行LRE以后可以开启Google Now，打电话主叫正常，但做被叫时无响应，主叫手机回铃音正常。

运行LRE以前基本通话数据功能正常，求教，多谢！

**Comment by FairyScript** [comment]
清空联系人存储的数据试一下
Moto Z2force同样的问题（但不是LRE引发的），我没有找到完美的解决办法
