### ISSUE TITLE
Xposed version support kitkat?

### ISSUE THREAD

**Issue by darkgentry** [GhostFlying/LocationReportEnabler#9]
I downloaded it from Xposed repo,but xposed reported the api is not support.

**Comment by wxg4net** [comment]
Android5+ 么

**Comment by GhostFlying** [comment]
Now it do not support kitkat as I do not have devices to test it. But I compile one for test, you can download to try if you have interest.

**Comment by wxg4net** [comment]
@GhostFlying  where?

**Comment by GhostFlying** [comment]
Download:  https://plus.google.com/112913363187242942924/posts/K4rAbPb9wTM

**Comment by wxg4net** [comment]
@GhostFlying 已测，反馈在G+

**Comment by darkgentry** [comment]
@GhostFlying OK,it works in kitkat.

**Comment by GhostFlying** [comment]
Ok, I will update this, thanks for your test.
